project_id = "yauanhuyeuekrippwpgh"

[functions.stock-data]
verify_jwt = false

[functions.upstox-auth]
verify_jwt = false

[functions.market-news]
verify_jwt = false

[functions.delta-trade]
verify_jwt = false

[functions.delta-account]
verify_jwt = false

[functions.nextbull-chat]
verify_jwt = false

[functions.yahoo-finance]
verify_jwt = false

[functions.delta-history]
verify_jwt = false

[functions.dhan-account]
verify_jwt = false

[functions.economic-calendar]
verify_jwt = false
